// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: GateServer.Varify.proto

#include "GateServer.Varify.pb.h"
#include "GateServer.Varify.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace GateServer {
namespace Varify {

static const char* VarifyServer_method_names[] = {
  "/GateServer.Varify.VarifyServer/GetVarifyCode",
};

std::unique_ptr< VarifyServer::Stub> VarifyServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VarifyServer::Stub> stub(new VarifyServer::Stub(channel, options));
  return stub;
}

VarifyServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetVarifyCode_(VarifyServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VarifyServer::Stub::GetVarifyCode(::grpc::ClientContext* context, const ::GateServer::Varify::GetVarifyReq& request, ::GateServer::Varify::GetVarifyRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GateServer::Varify::GetVarifyReq, ::GateServer::Varify::GetVarifyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVarifyCode_, context, request, response);
}

void VarifyServer::Stub::async::GetVarifyCode(::grpc::ClientContext* context, const ::GateServer::Varify::GetVarifyReq* request, ::GateServer::Varify::GetVarifyRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GateServer::Varify::GetVarifyReq, ::GateServer::Varify::GetVarifyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVarifyCode_, context, request, response, std::move(f));
}

void VarifyServer::Stub::async::GetVarifyCode(::grpc::ClientContext* context, const ::GateServer::Varify::GetVarifyReq* request, ::GateServer::Varify::GetVarifyRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVarifyCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GateServer::Varify::GetVarifyRsp>* VarifyServer::Stub::PrepareAsyncGetVarifyCodeRaw(::grpc::ClientContext* context, const ::GateServer::Varify::GetVarifyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GateServer::Varify::GetVarifyRsp, ::GateServer::Varify::GetVarifyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVarifyCode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GateServer::Varify::GetVarifyRsp>* VarifyServer::Stub::AsyncGetVarifyCodeRaw(::grpc::ClientContext* context, const ::GateServer::Varify::GetVarifyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVarifyCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

VarifyServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VarifyServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VarifyServer::Service, ::GateServer::Varify::GetVarifyReq, ::GateServer::Varify::GetVarifyRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VarifyServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GateServer::Varify::GetVarifyReq* req,
             ::GateServer::Varify::GetVarifyRsp* resp) {
               return service->GetVarifyCode(ctx, req, resp);
             }, this)));
}

VarifyServer::Service::~Service() {
}

::grpc::Status VarifyServer::Service::GetVarifyCode(::grpc::ServerContext* context, const ::GateServer::Varify::GetVarifyReq* request, ::GateServer::Varify::GetVarifyRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace GateServer
}  // namespace Varify

