// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: GateServer.Status.proto

#include "GateServer.Status.pb.h"
#include "GateServer.Status.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace GateServer {
namespace Status {

static const char* StatusServer_method_names[] = {
  "/GateServer.Status.StatusServer/GetChatServer",
  "/GateServer.Status.StatusServer/Login",
};

std::unique_ptr< StatusServer::Stub> StatusServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StatusServer::Stub> stub(new StatusServer::Stub(channel, options));
  return stub;
}

StatusServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetChatServer_(StatusServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(StatusServer_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StatusServer::Stub::GetChatServer(::grpc::ClientContext* context, const ::GateServer::Status::GetChatServerReq& request, ::GateServer::Status::GetChatServerRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GateServer::Status::GetChatServerReq, ::GateServer::Status::GetChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetChatServer_, context, request, response);
}

void StatusServer::Stub::async::GetChatServer(::grpc::ClientContext* context, const ::GateServer::Status::GetChatServerReq* request, ::GateServer::Status::GetChatServerRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GateServer::Status::GetChatServerReq, ::GateServer::Status::GetChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChatServer_, context, request, response, std::move(f));
}

void StatusServer::Stub::async::GetChatServer(::grpc::ClientContext* context, const ::GateServer::Status::GetChatServerReq* request, ::GateServer::Status::GetChatServerRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChatServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GateServer::Status::GetChatServerRsp>* StatusServer::Stub::PrepareAsyncGetChatServerRaw(::grpc::ClientContext* context, const ::GateServer::Status::GetChatServerReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GateServer::Status::GetChatServerRsp, ::GateServer::Status::GetChatServerReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetChatServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GateServer::Status::GetChatServerRsp>* StatusServer::Stub::AsyncGetChatServerRaw(::grpc::ClientContext* context, const ::GateServer::Status::GetChatServerReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetChatServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StatusServer::Stub::Login(::grpc::ClientContext* context, const ::GateServer::Status::LoginReq& request, ::GateServer::Status::LoginRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GateServer::Status::LoginReq, ::GateServer::Status::LoginRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void StatusServer::Stub::async::Login(::grpc::ClientContext* context, const ::GateServer::Status::LoginReq* request, ::GateServer::Status::LoginRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GateServer::Status::LoginReq, ::GateServer::Status::LoginRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void StatusServer::Stub::async::Login(::grpc::ClientContext* context, const ::GateServer::Status::LoginReq* request, ::GateServer::Status::LoginRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GateServer::Status::LoginRsp>* StatusServer::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::GateServer::Status::LoginReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GateServer::Status::LoginRsp, ::GateServer::Status::LoginReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GateServer::Status::LoginRsp>* StatusServer::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::GateServer::Status::LoginReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

StatusServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusServer::Service, ::GateServer::Status::GetChatServerReq, ::GateServer::Status::GetChatServerRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GateServer::Status::GetChatServerReq* req,
             ::GateServer::Status::GetChatServerRsp* resp) {
               return service->GetChatServer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StatusServer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StatusServer::Service, ::GateServer::Status::LoginReq, ::GateServer::Status::LoginRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StatusServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GateServer::Status::LoginReq* req,
             ::GateServer::Status::LoginRsp* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
}

StatusServer::Service::~Service() {
}

::grpc::Status StatusServer::Service::GetChatServer(::grpc::ServerContext* context, const ::GateServer::Status::GetChatServerReq* request, ::GateServer::Status::GetChatServerRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StatusServer::Service::Login(::grpc::ServerContext* context, const ::GateServer::Status::LoginReq* request, ::GateServer::Status::LoginRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace GateServer
}  // namespace Status

